version: '3.4'

services:
  hometg:
    build:
      context: .
      dockerfile: HomeTG.API/Dockerfile
    pull_policy: build
    ports:
      - "5234:5234"
    volumes:
      - /home/clem/docker/hometg/data/hometg:/root/.local/share/hometg/DB/hometg
    environment:
      "ASPNETCORE_ENVIRONMENT": "linux"
      # Optional way to overwrite database connection.
       "ConnectionStrings__Sqlite": "Data Source=/usr/share/hometg/Collection.db"
       "provider": "Sqlite"
      "ConnectionStrings__Postgres": "Host=database;Username=hometg;Password=supersecretpassword;Database=hometg_db"
      "provider": "Postgres"
    networks:
      - public
      - private
    depends_on:
      - database
    restart: "unless-stopped"

  hometg-react:
    build:
      context: .
      dockerfile: HomeTG.React/Dockerfile
    environment:
      REACT_APP_PROXY_HOST: "http://hometg"
      WDS_SOCKET_PORT: 0
    pull_policy: build
    ports:
      - "5235:5235"
    networks:
      - public
    depends_on:
      - hometg
    restart: unless-stopped

  # Remove this section if you want to use Sqlite instead.
  # Word of warning: Sqlite is much slower when it comes to manipulating the DB.
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hometg
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: hometg_db
    networks:
      - private
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: "unless-stopped"

networks:
  public:
  private:

volumes:
  postgres-data:
